//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int idFactura { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> idVendedor { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual Clientes Clientes { get; set; }
        public virtual Vendedor Vendedor { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
