//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaCliente
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Apellido_Paterno { get; set; }
        public string Apellido_Materno { get; set; }
        public string Genero { get; set; }
        public Nullable<int> Numero_de_telefono { get; set; }
        public string Municipio { get; set; }
        public string Calle { get; set; }
        public Nullable<int> Numero_domicilio { get; set; }
    }
}
