//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaFactura
    {
        public int Nro_Factura { get; set; }
        public string Cliente { get; set; }
        public string Vendedor { get; set; }
        public string Producto { get; set; }
        public Nullable<decimal> Precio_Unitario { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public Nullable<int> ID_Vendedor { get; set; }
        public Nullable<int> ID_Producto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
